apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  mongodb-stateful
  labels:
    app: mongodb
spec:
  serviceName: "mongodb-service" 
  replicas: 1
  selector:
    matchLabels:
      app: mongodb    
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - 
          name: mongodb
          image: mongo
          imagePullPolicy: "Always"
          env:
            - 
              name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - 
              name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password  
            - 
              name: MONGODB_DATABASE
              value: admin
          ports:
            - 
              containerPort: 27017
              name: "mongodb"
          volumeMounts:
            - 
              name: "mongodb-persistent-storage"
              mountPath: "/data/db"   
      volumes: 
        - 
          name: "mongodb-persistent-storage"
          persistentVolumeClaim: 
            claimName: "mongodb-pvc"              
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
